site_name: Processo software
repo_url: https://github.com/Firi0n/appunti-software-engineering
repo_name: GitHub
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.footer
    - toc.integrate # Enable TOC (auto index)
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md
  - d2:
      cache: False
      layout: elk
      theme: 0
      dark_theme: 200
      sketch: False
      pad: 10
      scale: 1.0

# Markdown extensions
markdown_extensions:
  - toc:
      baselevel: 2 # Starts ToC from <h2> instead of <h1>
      permalink: "#" # Title linking
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.superfences: # Mermaid support
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true # LaTeX support

# LaTeX support (MathJax)
extra_javascript:
  - overrides/custom-mermaid-elk.mjs
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js

extra_css:
  - overrides/main.css

copyright: "Copyright &copy; 2025 - 2026 Firi0n"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Firi0n/
      name: firi0n on GitHub
